# Generated by Django 3.2.5 on 2022-04-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk', '0003_comments_contributors_issues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
